spring:
  
  datasource:
    url: jdbc:h2:mem:testes2
    username : sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show.sql: true
    properties.hibernate.format_sql : true

  h2:
    console:
      enabled: true
      path: /h2